### ISSUE TITLE
Bug in parse-docker-compose-volumes with special characters

### ISSUE THREAD

**Issue by andyneff** [VisionSystemsInc/vsi_common#390]
If a path has a special character in it, such as a tab, the output of `docker-compose config` is

```
services:
  test_hay:
    volumes:
    - "/tmp/f o  o\tbar/test-docker_functions.bsh-3685004.q7YBc5ev/test4:/src:rw"
    - "/tmp/f o  o\tbar/test-docker_functions.bsh-3591660.0AqqVZoq/test4/foo\"b'ar:/src:rw"
    - "/tmp/f o  o\tbar/test-docker_functions.bsh-3591660.0AqqVZoq/test4/f\U0001F61B\
      oo\"b'ar:/src:rw"
```

`parse-docker-compose-volumes` does not currently handle this for long or short formats.

Unicode is an issue, and not generally supported.
